### ISSUE TITLE
Add User Profile Section

### ISSUE THREAD

**Issue by pratyush090506** [Abhilash107/Sidebar#12]
I'd like to add a user profile section at the top of the sidebar, showing the user's avatar, name, and a dropdown with options like "Settings" and "Log out."

Can you please assign this task to me?

**Comment by Anurag-singh-thakur** [comment]
can you assign it to me ...I am a UI designer  followed by the developer skills

**Comment by Abhilash107** [comment]
@pratyush090506 Could you please provide more details?

**Comment by Abhilash107** [comment]
> can you assign it to me ...I am a UI designer followed by the developer skills

@Anurag-singh-thakur This operates on a first-come, first-served basis. You can raise a new issue and request it.
