### ISSUE TITLE
Menu Icon Animation on Hover

### ISSUE THREAD

**Issue by pratyush090506** [Abhilash107/Sidebar#14]
A subtle animation of the icon when hovering over menu items adds a dynamic touch to the sidebar.

Can you please assign this task to me?

**Comment by Piyush-Goenka** [comment]
Hey @Abhilash107 
Please assign this issue to me

**Comment by Abhilash107** [comment]
@pratyush090506 You have been spamming in the issue section. If you want to contribute, please create one issue and mention the problems you want to fix.
