### ISSUE TITLE
Add Modern Contact Page

### ISSUE THREAD

**Issue by Abhi-Jeeet** [Abhilash107/Sidebar#20]
Contact Page not available.
So I would like to help you out in creating a Modern Contact Page.
Sample pic-
![Screenshot 2024-10-14 104503](https://github.com/user-attachments/assets/f20e0289-9b26-4885-8901-ffa988fdbdc0)

Please assign this to me and mark it as hactoberfest.

**Comment by Abhilash107** [comment]
Go ahead but avoid using this theme, it doesn't match the main page.
