### ISSUE TITLE
Animations: Add CSS animations for smoother transitions when opening and closing the sidebar.

### ISSUE THREAD

**Issue by Pratham-Onkar-Singh** [Abhilash107/Sidebar#3]
Issue Description: The current sidebar lacks smooth transitions when opening and closing, resulting in abrupt changes to the UI. Adding CSS animations would enhance the user experience by making these transitions smoother and more visually appealing.

Expected Behavior: When the sidebar opens and closes, it should use CSS animations to create a smooth transition effect. This would improve the overall flow and usability of the interface.

Steps to Recreate:

- Go to the website Sidebar.
- Click on the sidebar toggle button to open the sidebar.
- Observe that the sidebar opens abruptly without a smooth transition.
- Click the toggle button again to close the sidebar and observe the abrupt closing action.

Request: Kindly assign this issue to me (Pratham Onkar Singh) so I can resolve it.

**Comment by Abhilash107** [comment]
@Pratham-Onkar-Singh Hey, I've assigned it to you.
