### ISSUE TITLE
Add Divider Under Each Item in the Sidebar and add scrollbar

### ISSUE THREAD

**Issue by abdullah-k18** [Abhilash107/Sidebar#38]
I'll add a divider under each of the item in the sidebar. Also i'll add a scrollbar and edit it according to the styles. Change the cursor to pointer when hovered over any of the item in the sidebar. Also create a who tile for the social media icons.
![Sidebar - Google Chrome 10_14_2024 5_05_59 PM](https://github.com/user-attachments/assets/a656d88e-9a9c-47c0-8591-62fbd21e9ec6)

**Comment by Abhilash107** [comment]
hey @abdullah-k18 ,  after cloning the repo and creating your new branch, just use "git pull origin main" to fetch the latest changes from the main branch and ensure your local copy is up-to-date with the latest commits.

Kindly include the issueTag in your PR.
