### ISSUE TITLE
Create a FAQ section

### ISSUE THREAD

**Issue by imadityayadav** [Abhilash107/Sidebar#48]
Creating a new FAQ section for the app

**Comment by imadityayadav** [comment]
Could  you please assign me this issue

**Comment by Abhilash107** [comment]
There's already a FAQ section on site.

**Comment by imadityayadav** [comment]
its there but there is nothing when we click on it i want to make that page

**Comment by Abhilash107** [comment]
> its there but there is nothing when we click on it i want to make that page
There have been some contents added to it.
