### ISSUE TITLE
there are 2 menu in the same sidebar

### ISSUE THREAD

**Issue by parthtaneja0001** [Abhilash107/Sidebar#52]
there  is a heading of menu and and the first element in the sidebar's name is also "menu". we can change it to something like home also the login element is concatenated in a single word ill change it too so please assign it to me

**Comment by Abhilash107** [comment]
No, it has been corrected. I suggest you should always use "git pull origin main" before changing in codebases, it pulls origin main before making changes ensure that the local codebase is up-to-date with the remote repository
