### ISSUE TITLE
Design Improvements

### ISSUE THREAD

**Issue by Darshan-SD** [Abhilash107/Sidebar#62]
I would like to improve the sidebar with the following changes:
1. Add a blurred background to the sidebar.
2. Fix the overlay of login and Menu text.
3. Change the color of social media icons according to their brand color on hover. E.g., YouTube icon with a red color
4. Add animation to the close button on hover.
5. Remove the white box shadow on the sidebar

Please assign this issue with the hacktoberfest-accepted tag. Thanks

**Comment by Abhilash107** [comment]
Thanks for addressing the issue, but for now, I don't want any feature enhancements in my projects.
