### ISSUE TITLE
Add Hover for Options effect.

### ISSUE THREAD

**Issue by prathameshrp** [Abhilash107/Sidebar#63]
![Applying_Shadow_Effects_on_Hover_eb00763745](https://github.com/user-attachments/assets/6e71b4b6-8a87-41d5-90f1-17af22281c99)

Add this type of effects on menu list options. 
Also possibly add some effects on hover for the menu options.

**Comment by Abhilash107** [comment]
Thanks for addressing the issue, but for now, I don't want any feature enhancements in my projects.

**Comment by prathameshrp** [comment]
okay! sure.
