### ISSUE TITLE
padding problem in animation

### ISSUE THREAD

**Issue by parthtaneja0001** [Abhilash107/Sidebar#64]
while clicking on username/email/password the animation which comes places these headings on top of box however its not given propper padding as i highlighted in the image below so i cam fix it
<img width="561" alt="Screenshot 2024-10-15 at 1 03 17 AM" src="https://github.com/user-attachments/assets/15d754ad-1bff-42a1-a648-27498cb228bf">

**Comment by MannVaswani4** [comment]
I would like to work on this @Abhilash107 . May you please assign it to me.

**Comment by Abhilash107** [comment]
> I would like to work on this @Abhilash107 . May you please assign it to me.

Hey @MannVaswani4 actually I hv already assigned to @parthtaneja0001.
