### ISSUE TITLE
Include CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by Dhruv-Davda** [Abhilash107/Sidebar#67]
I would like to add CODE_OF_CONDUCT file in your repository. 

@Abhilash107    Could you please assign me this issue ?

**Comment by Abhilash107** [comment]
> I would like to add CODE_OF_CONDUCT file in your repository. 
> 
> @Abhilash107    Could you please assign me this issue ? 

Please check the discussion tab.

**Comment by Dhruv-Davda** [comment]
Ok, got it.

**Comment by Abhilash107** [comment]
Thanks for raising the issue.
