### ISSUE TITLE
Update Social links in that website 

### ISSUE THREAD

**Issue by sambhavbohra** [Abhilash107/Sidebar#8]
Will update social links !! 
Can you please share links of
1. Facebook
2. twitter
3. instagram
4. linkdin
5. github
6. youtube

**Comment by sambhavbohra** [comment]
If you dont have social accounts of this website or personal one then will update with login page of those websites !!

**Comment by Anurag-singh-thakur** [comment]
can you assign it to me I am a MERN Stack developer . Here is an example of what i made to ensure that i am a good fit for the project. Link (https://voting-app-frontend-67ba.onrender.com/)

**Comment by Abhilash107** [comment]
Hey @sambhavbohra , no need to work on social links, Btw Thanks for raising the issue
