### ISSUE TITLE
Add Theme Toggle for Dark/Light Mode

### ISSUE THREAD

**Issue by AdarshRaj241408** [Abhilash107/Sidebar#81]
Description:
I would like to propose adding a theme toggle feature to the project. This feature will allow users to switch between dark and light themes, enhancing usability and accessibility.

Implementation Details:
- Toggle Button: A checkbox can be used as a toggle switch for dark/light modes.
- JavaScript Functionality: Use a few lines of JavaScript to manage the theme switch.
- Local Storage: Implement localStorage to remember the user's theme preference across sessions.

Issue:
The current implementation of the theme toggle feature does not effectively showcase its potential due to the fixed background image. This raises a question about whether the background image should remain constant or if it should change dynamically based on the selected theme.

Solution:
- Dynamic Background Images: completely diferent background for light and dark mode
- Consistent Aesthetic:

**Comment by Abhilash107** [comment]
Hello, everyone! 👋

I am temporarily pausing the acceptance of new Issues and Pull Requests as I focus on the server side of the project. During this period, my priority will be improving the backend, performance,

While I'm excited about the upcoming changes and enhancements, I kindly ask for your patience and understanding as I work behind the scenes.

Please stay tuned for updates—once this phase is complete, I'll reopen the repository for contributions and feedback.

Thank you for your support! 🙏
