### ISSUE TITLE
The Social media Handles are not is visible position

### ISSUE THREAD

**Issue by Harshcbx8** [Abhilash107/Sidebar#82]
![Screenshot 2024-10-19 123127](https://github.com/user-attachments/assets/ee92b7c9-4c86-4bbd-b88a-acb5c192366f)
In the side bar the social media handle are places behind the other options i will make the seperate sections in the side bar to show all social media handles properly. Will you assign work to me.

**Comment by Harshcbx8** [comment]
@Abhilash107  Kindly respond to me so i can start work on it

**Comment by Abhilash107** [comment]
> @Abhilash107  Kindly respond to me so i can start work on it

Kindly check the announcement in discussion tab.

**Comment by Abhilash107** [comment]
> > @Abhilash107  Kindly respond to me so i can start work on it
> 
> Kindly check the announcement in discussion tab.
