### ISSUE TITLE
Adding all contributors to readme.md

### ISSUE THREAD

**Issue by navyaajainnn** [Abhilash107/Sidebar#89]
Description: I would like to propose adding an "All Contributors" section to the README.md file to recognize the valuable contributions made by all contributors to this project.

Rationale:
This section will help to:

Acknowledge Contributions: Open-source projects thrive on the efforts of many contributors. By adding this section, we can give recognition to the individuals who have contributed code, documentation, design, or any other improvements.
Encourage More Contributions: Recognizing contributors publicly often motivates others to get involved, which can help grow the community around the project.
Improve Transparency: It creates an open acknowledgment of who has helped improve the project, reflecting a spirit of collaboration.

**Comment by navyaajainnn** [comment]
hey, @Abhilash107 , please assign this issue to me under hacktober tag. Thanks :)

**Comment by Abhilash107** [comment]
Hey @navyaajainnn, kindly check the announcement tab in the discussion section.
